### ISSUE TITLE
Decimal parsing error

### ISSUE THREAD

**Issue by ErikKaum** [jjduhamel/bcl#1]
**Describe the bug**
Parsing decimal places returns error in wager input html element.

**Provide the contract address**
If applicable.  You can find this in the URL.

**To Reproduce**
Screen shot should give a clear picture.

<img width="1403" alt="Screenshot 2022-07-23 at 11 23 25" src="https://user-images.githubusercontent.com/24875419/180597073-f47f5a29-8d58-432a-8c0b-881aadb5dff9.png">

**Comment by jjduhamel** [comment]
Yes I'm aware of this.  It needs to convert the number to wei on the frontend.  Will leave this open until it get's sorted.

**Comment by jjduhamel** [comment]
fixed
